// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsjFYse5Lv2kvxfbx-g1eZ9LizfyBx20U',
    appId: '1:250438085834:web:5684e39befbba052131833',
    messagingSenderId: '250438085834',
    projectId: 'books-app-17597',
    authDomain: 'books-app-17597.firebaseapp.com',
    storageBucket: 'books-app-17597.appspot.com',
    measurementId: 'G-B9GK3ZN0ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKsXJYC68NCSR_UsufmtyXybx08mZBps',
    appId: '1:250438085834:android:aef42cfa446522be131833',
    messagingSenderId: '250438085834',
    projectId: 'books-app-17597',
    storageBucket: 'books-app-17597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZFPHAyFoi7A40cT4TtCd3yPeg0CJj44',
    appId: '1:250438085834:ios:fa6f880162d1825a131833',
    messagingSenderId: '250438085834',
    projectId: 'books-app-17597',
    storageBucket: 'books-app-17597.appspot.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZFPHAyFoi7A40cT4TtCd3yPeg0CJj44',
    appId: '1:250438085834:ios:fa6f880162d1825a131833',
    messagingSenderId: '250438085834',
    projectId: 'books-app-17597',
    storageBucket: 'books-app-17597.appspot.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsjFYse5Lv2kvxfbx-g1eZ9LizfyBx20U',
    appId: '1:250438085834:web:1f3915bc272768d9131833',
    messagingSenderId: '250438085834',
    projectId: 'books-app-17597',
    authDomain: 'books-app-17597.firebaseapp.com',
    storageBucket: 'books-app-17597.appspot.com',
    measurementId: 'G-FT61388YVT',
  );
}
